site_name: Saiblo 平台开发维护手册
nav:
- 概览: 'index.md' 
- 运维手册:
    - '平台部署': 'ops/deployment.md'
    - '反向代理': 'ops/proxy.md'
    - '定时对局抽取': 'ops/auto_match.md'
    - '评测机部署': 'ops/judger.md'
    - 'Wiki 管理': 'ops/wiki.md'
- 开发手册:
    - '平台架构': 'dev/arch.md'
    - '前端': 'dev/frontend.md'
    - '后端': 'dev/backend.md'
    - '评测端': 'dev/judger.md'
    - '前端与后端': 'dev/frontend2backend.md'
    - '前端与评测端': 'dev/frontend2judger.md'
    - '后端与评测端': 'dev/backend2judger.md'
- 前端手册:
    - '概述': 'frontend/website-frontend.md'
    - '用户系统': 'frontend/website-frontend-user.md'
    - '比赛系统': 'frontend/website-frontend-contest.md'
    - '游戏系统': 'frontend/website-frontend-game.md'
    - '小组系统': 'frontend/website-frontend-group.md'
    - '部件': 'frontend/website-frontend-component.md'
    - '代码系统': 'frontend/website-frontend-code.md'
theme: readthedocs
